language: python
python:
  - "3.11"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y default-libmysqlclient-dev build-essential pkg-config
install:
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - pytest
  - coverage run --source=core -m pytest
after_success:
  - coveralls
