# -*- coding: utf-8 -*-
"""
    demo_go
    ~~~~~~~
    Go 修复函数和可控输入源配置
    :author:    LoRexxar <LoRexxar@gmail.com>
    :homepage:  https://github.com/LoRexxar/Kunlun-M
    :license:   MIT, see LICENSE for more details.
    :copyright: Copyright (c) 2017 LoRexxar. All rights reserved
"""
GO_IS_REPAIR_DEFAULT = {
    "html.EscapeString": [3000, 3006],
    "html.Escape": [3000, 3006],
    "template.HTMLEscapeString": [3000, 3006],
    "template.JSEscapeString": [3000, 3006],
    "url.QueryEscape": [3000, 3001],
    "url.PathEscape": [3000, 3001],
    "strconv.Atoi": [3000, 3001],
    "strconv.Itoa": [3000],
    "strconv.FormatInt": [3000],
    "json.Marshal": [3006],
    "json.HTMLEscape": [3000, 3006],
    "regexp.QuoteMeta": [3000, 3001],
    "sanitizer.Sanitize": [3000, 3006],
    "bluemonday.StrictPolicy.Sanitize": [3000, 3006],
    "bluemonday.UGCPolicy.Sanitize": [3000, 3006],
    "db.Query": [3002],
    "db.Exec": [3002],
    "tx.Exec": [3002],
    "tx.Query": [3002],
    "sqlx.Query": [3002],
    "sqlx.Exec": [3002],
    "gorm.DB.Where": [3002],
    "gorm.DB.Raw": [3002],
    "gorm.DB.Exec": [3002],
}

GO_IS_CONTROLLED_DEFAULT = [
    # net/http - http.Request
    "r.URL.Query()",
    "r.FormValue",
    "r.PostFormValue",
    "r.Header.Get",
    "r.Body",
    "r.URL.Path",
    "r.URL.RawPath",
    "r.Host",
    "r.RemoteAddr",
    "r.UserAgent",
    "r.Referer",
    "r.Method",
    "r.URL.RawQuery",
    "r.URL.Fragment",
    "r.URL.Host",
    "r.URL.Scheme",
    "r.Cookies",
    "r.Cookie",
    "r.Context",
    "r.Form",
    "r.PostForm",
    "r.MultipartForm",
    "r.TransferEncoding",
    "request.FormValue",
    "request.PostFormValue",
    "request.URL.Query",
    "request.URL.Path",
    "request.Header",
    "request.Body",
    "request.Host",
    "request.UserAgent",
    "request.Referer",
    "request.Cookies",
    "request.Cookie",
    # os
    "os.Args",
    "os.Getenv",
    "os.Stdin",
    # flag
    "flag.String",
    "flag.Int",
    "flag.Bool",
    "flag.Float64",
    # Gin framework
    "c.Query",
    "c.DefaultQuery",
    "c.Param",
    "c.PostForm",
    "c.DefaultPostForm",
    "c.GetHeader",
    "c.GetCookie",
    "c.ShouldBind",
    "c.ShouldBindJSON",
    "c.ShouldBindQuery",
    "c.ShouldBindUri",
    "c.ShouldBindHeader",
    "c.ShouldBindWith",
    "c.BindJSON",
    "c.BindQuery",
    "c.BindUri",
    "c.BindHeader",
    "c.Request.URL",
    "c.Request.Header",
    "c.Request.Body",
    "c.Request.FormValue",
    "ctx.Query",
    "ctx.DefaultQuery",
    "ctx.Param",
    "ctx.PostForm",
    "ctx.GetHeader",
    "ctx.GetCookie",
    # Echo framework
    "echo.QueryParams",
    "echo.FormValue",
    "echo.QueryParam",
    "echo.PathParam",
    "echo.FormParams",
    "echo.Cookies",
    "echo.Cookie",
    "echo.Header",
    "echo.Context.QueryParam",
    "echo.Context.Param",
    "echo.Context.FormValue",
    "echo.Context.FormParams",
    "echo.Context.Cookie",
    "echo.Context.Cookies",
    "echo.Context.GetHeader",
    # Fiber framework
    "fiber.Query",
    "fiber.Params",
    "fiber.Body",
    "fiber.Get",
    "fiber.Cookies",
    "fiber.Locals",
    # Beego framework
    "beego.Input",
    "beego.GetString",
    "beego.GetStrings",
    "beego.GetStrings",
    "beego.Ctx.Input.Query",
    "beego.Ctx.Input.Param",
    "beego.Ctx.Input.Header",
    "beego.Ctx.Input.Cookie",
    "beego.Ctx.Input.RequestBody",
    # Chi router
    "chi.URLParam",
    "chi.RouteContext",
    # Gorilla/mux
    "mux.Vars",
    # io/ioutil
    "ioutil.ReadAll",
    "io.ReadAll",
    # Context
    "context.Value",
    "ctx.Value",
]
