# -*- coding: utf-8 -*-
# @Time    : 2019/5/14 18:36
# @Author  : KunLun-M
# @File    : functions.py
# @Contact : lorexxar@gmail.com

"""
    C/C++ 内置函数字典
    用于标识标准库函数，在分析中跳过这些函数的定义追踪。
    value = 1 表示内置函数。
"""

function_dict = {
    # ============ stdio.h ============
    "printf": 1,
    "fprintf": 1,
    "sprintf": 1,
    "snprintf": 1,
    "scanf": 1,
    "fscanf": 1,
    "sscanf": 1,
    "fopen": 1,
    "fclose": 1,
    "fread": 1,
    "fwrite": 1,
    "fgets": 1,
    "fputs": 1,
    "fputc": 1,
    "fgetc": 1,
    "getc": 1,
    "getchar": 1,
    "gets": 1,
    "puts": 1,
    "putchar": 1,
    "fseek": 1,
    "ftell": 1,
    "rewind": 1,
    "feof": 1,
    "ferror": 1,
    "clearerr": 1,
    "fflush": 1,
    "setbuf": 1,
    "setvbuf": 1,
    "ungetc": 1,
    "popen": 1,
    "pclose": 1,
    "tmpfile": 1,
    "tmpnam": 1,
    "remove": 1,
    "rename": 1,
    "getline": 1,
    "getline_r": 1,

    # ============ stdlib.h ============
    "malloc": 1,
    "calloc": 1,
    "realloc": 1,
    "free": 1,
    "abort": 1,
    "exit": 1,
    "atexit": 1,
    "atoi": 1,
    "atol": 1,
    "atof": 1,
    "strtol": 1,
    "strtoul": 1,
    "strtod": 1,
    "strtof": 1,
    "strtoll": 1,
    "strtoull": 1,
    "strtoq": 1,
    "strtouq": 1,
    "rand": 1,
    "srand": 1,
    "abs": 1,
    "labs": 1,
    "div": 1,
    "ldiv": 1,
    "qsort": 1,
    "bsearch": 1,
    "getenv": 1,
    "system": 1,
    "bsearch": 1,

    # ============ string.h ============
    "memcpy": 1,
    "memmove": 1,
    "memset": 1,
    "memcmp": 1,
    "memchr": 1,
    "strlen": 1,
    "strcpy": 1,
    "strncpy": 1,
    "strcat": 1,
    "strncat": 1,
    "strcmp": 1,
    "strncmp": 1,
    "strcasecmp": 1,
    "strncasecmp": 1,
    "strchr": 1,
    "strrchr": 1,
    "strstr": 1,
    "strtok": 1,
    "strtok_r": 1,
    "strsep": 1,
    "strdup": 1,
    "strndup": 1,
    "strerror": 1,
    "strpbrk": 1,
    "strspn": 1,
    "strcspn": 1,

    # ============ ctype.h ============
    "isalpha": 1,
    "isdigit": 1,
    "isalnum": 1,
    "isspace": 1,
    "isupper": 1,
    "islower": 1,
    "ispunct": 1,
    "isprint": 1,
    "isgraph": 1,
    "iscntrl": 1,
    "isxdigit": 1,
    "toupper": 1,
    "tolower": 1,

    # ============ math.h ============
    "sin": 1,
    "cos": 1,
    "tan": 1,
    "asin": 1,
    "acos": 1,
    "atan": 1,
    "atan2": 1,
    "sqrt": 1,
    "pow": 1,
    "exp": 1,
    "log": 1,
    "log10": 1,
    "ceil": 1,
    "floor": 1,
    "fabs": 1,
    "fmod": 1,
    "abs": 1,

    # ============ unistd.h (POSIX) ============
    "read": 1,
    "write": 1,
    "close": 1,
    "dup": 1,
    "dup2": 1,
    "pipe": 1,
    "fork": 1,
    "execvp": 1,
    "execv": 1,
    "execl": 1,
    "execlp": 1,
    "execle": 1,
    "execvpe": 1,
    "fexecve": 1,
    "execve": 1,
    "getpid": 1,
    "getppid": 1,
    "getuid": 1,
    "getgid": 1,
    "chdir": 1,
    "getcwd": 1,
    "sleep": 1,
    "usleep": 1,
    "alarm": 1,
    "access": 1,

    # ============ signal.h ============
    "signal": 1,
    "raise": 1,
    "kill": 1,

    # ============ socket (sys/socket.h) ============
    "socket": 1,
    "bind": 1,
    "listen": 1,
    "accept": 1,
    "connect": 1,
    "recv": 1,
    "send": 1,
    "recvfrom": 1,
    "sendto": 1,
    "shutdown": 1,
    "setsockopt": 1,
    "getsockopt": 1,

    # ============ netdb.h ============
    "gethostbyname": 1,
    "gethostbyaddr": 1,
    "getaddrinfo": 1,
    "freeaddrinfo": 1,
    "getnameinfo": 1,

    # ============ pthread ============
    "pthread_create": 1,
    "pthread_join": 1,
    "pthread_detach": 1,
    "pthread_mutex_lock": 1,
    "pthread_mutex_unlock": 1,
    "pthread_mutex_init": 1,
    "pthread_cond_wait": 1,
    "pthread_cond_signal": 1,
    "pthread_cond_broadcast": 1,

    # ============ spawn/posix ============
    "posix_spawn": 1,
    "posix_spawnp": 1,

    # ============ time.h ============
    "time": 1,
    "clock": 1,
    "difftime": 1,
    "mktime": 1,
    "strftime": 1,
    "localtime": 1,
    "gmtime": 1,
    "asctime": 1,
    "ctime": 1,

    # ============ errno.h ============
    "strerror": 1,

    # ============ dirent.h ============
    "opendir": 1,
    "closedir": 1,
    "readdir": 1,
    "rewinddir": 1,
    "telldir": 1,
    "seekdir": 1,

    # ============ C++ iostream (自定义，非标准库) ============
    # std::cin, std::cout, std::cerr 等不是函数调用，暂不列入
}
